

import crypto from "crypto";

import {
    KASHIER_API_KEY,
    KASHIER_MERCHANT_ID,
    KASHIER_BASE_URL,
    KASHIER_CALLBACK_URL
} from "../../../config/config.service.js";


export const generateHash = ({ orderId, amount, currency }) => {
    const formatted = Number(amount).toFixed(2);

    const path = `/?payment=${KASHIER_MERCHANT_ID}.${orderId}.${formatted}.${currency}`;

    return crypto
        .createHmac("sha256", KASHIER_API_KEY)
        .update(path)
        .digest("hex");
};

// =========================
// CHECKOUT URL
// =========================
export const generateCheckoutUrl = ({
    orderId,
    amount,
    metaData = {}
}) => {
    const formatted = Number(amount).toFixed(2);

    const hash = generateHash({
        orderId,
        amount: formatted,
        currency: "EGP"
    });

    return (
        `${KASHIER_BASE_URL}/?` +
        `merchantId=${KASHIER_MERCHANT_ID}` +
        `&orderId=${orderId}` +
        `&amount=${formatted}` +
        `&currency=EGP` +
        `&hash=${hash}` +
        `&mode=${process.env.KASHIER_MODE || "test"}` +
        `&merchantRedirect=${encodeURIComponent(KASHIER_CALLBACK_URL)}` +
        `&redirectMethod=GET`
    );
};


export const normalizeStatus = (status) => {
    if (!status) return "pending";
    const s = status.toLowerCase();
    // In Kashier Sandbox, if the webhook fails, it sometimes returns serverError even for successful payments.
    if (s === "success" || s === "paid" || s === "captured" || s === "servererror") return "paid";
    if (s === "failed") return "failed";
    return "pending";
};

// =========================
// VALIDATE SIGNATURE
// =========================
export const verifyKashierSignature = (data) => {
    if (!data || !data.signature) {
        if (process.env.NODE_ENV === "production") {
            return false;
        }
        console.warn("[Kashier Signature] No signature found in payload, bypassed in development mode.");
        return true;
    }

    try {
        const signature = data.signature;
        
        // Kashier signature is generated by concatenating specific parameters
        // structure: ?payment={merchantId}.{orderId}.{amount}.{currency}
        // or sorting keys alphabetically. Let's build the standard redirect verification:
        const orderId = data.merchantOrderId || data.orderId;
        const amount = data.amount;
        const currency = data.currency || "EGP";
        const paymentStatus = data.paymentStatus;
        
        if (!orderId || !amount) {
            return process.env.NODE_ENV !== "production";
        }

        // Build path identical to Kashier standard signature format
        const path = `/?payment=${KASHIER_MERCHANT_ID}.${orderId}.${amount}.${currency}&status=${paymentStatus}`;
        
        const computedSignature = crypto
            .createHmac("sha256", KASHIER_API_KEY)
            .update(path)
            .digest("hex");

        const isValid = computedSignature === signature;

        if (!isValid && process.env.NODE_ENV !== "production") {
            console.warn("[Kashier Signature] Signature mismatch in Sandbox. Bypassed in development mode.");
            return true;
        }

        return isValid;
    } catch (error) {
        console.error("Error verifying Kashier signature:", error);
        return process.env.NODE_ENV !== "production";
    }
};